<?php
// database/seeders/KalenderLiturgiSeeder.php

namespace Database\Seeders;

use App\Models\KalenderLiturgiHari;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class KalenderLiturgiSeeder extends Seeder
{
    public function run(): void
    {
        // Nonaktifkan foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        
        // Truncate table terlebih dahulu
        Schema::disableForeignKeyConstraints();
        KalenderLiturgiHari::truncate();
        Schema::enableForeignKeyConstraints();
        
        $data = [
            // ============================================================
            // JUNI 2026 (1 - 30 Juni)
            // ============================================================
            ['tanggal' => '2026-06-01', 'keterangan_hari' => 'Hari Biasa, Peringatan Santa Maria', 'warna_liturgi' => 'putih', 'bacaan1' => '2Ptr 1:2-7', 'mazmur_tanggapan' => 'Mzm 91:1-2,14-15,16', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mrk 12:1-12', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-02', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Ptr 3:11-15a,17-18', 'mazmur_tanggapan' => 'Mzm 90:2-3,4,10,14,16', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mrk 12:13-17', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-03', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Karolus Lwanga dkk', 'warna_liturgi' => 'merah', 'bacaan1' => '2Tim 1:1-3,6-12', 'mazmur_tanggapan' => 'Mzm 123:1b-2,3-4', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mrk 12:18-27', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-04', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Tim 2:8-15', 'mazmur_tanggapan' => 'Mzm 25:4-5,8-9,10,14', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mrk 12:28-34', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-05', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Bonifasius', 'warna_liturgi' => 'merah', 'bacaan1' => '2Tim 3:10-17', 'mazmur_tanggapan' => 'Mzm 119:157,160,161,165,166,168', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mrk 12:35-37', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-06', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Tim 4:1-8', 'mazmur_tanggapan' => 'Mzm 71:8-9,14-15,16-17,22', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mrk 12:38-44', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-07', 'keterangan_hari' => 'Minggu Biasa X', 'warna_liturgi' => 'hijau', 'bacaan1' => '1Raj 17:17-24', 'mazmur_tanggapan' => 'Mzm 30:2,4,5-6,11,12,13', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 7:11-17', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-08', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '1Raj 17:1-6', 'mazmur_tanggapan' => 'Mzm 121:1-2,3-4,5-6,7-8', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 5:1-12', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-09', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '1Raj 17:7-16', 'mazmur_tanggapan' => 'Mzm 4:2-3,4-5,7-8', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 5:13-16', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-10', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '1Raj 18:20-39', 'mazmur_tanggapan' => 'Mzm 16:1b-2,4,5,8,11', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 5:17-19', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-11', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Barnabas', 'warna_liturgi' => 'merah', 'bacaan1' => 'Kis 11:21b-26; 13:1-3', 'mazmur_tanggapan' => 'Mzm 98:1,2-3,3-4,5-6', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 10:7-13', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-12', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '1Raj 19:9a,11-16', 'mazmur_tanggapan' => 'Mzm 27:7-8,8-9,13-14', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 5:27-32', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-13', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Antonius dari Padua', 'warna_liturgi' => 'putih', 'bacaan1' => '1Raj 19:19-21', 'mazmur_tanggapan' => 'Mzm 16:1b-2,3,5,7-8,9-10', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 5:33-37', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-14', 'keterangan_hari' => 'Minggu Biasa XI', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Sam 12:7-10,13', 'mazmur_tanggapan' => 'Mzm 32:1-2,5,7,11', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 7:36-8:3', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-15', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '1Raj 21:1-16', 'mazmur_tanggapan' => 'Mzm 5:2-3,4-5,6-7', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 5:38-42', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-16', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '1Raj 21:17-29', 'mazmur_tanggapan' => 'Mzm 51:3-4,5-6,11,16', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 5:43-48', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-17', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Raj 2:1,6-14', 'mazmur_tanggapan' => 'Mzm 31:20,21,24', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 6:1-6,16-18', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-18', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Sir 48:1-14', 'mazmur_tanggapan' => 'Mzm 97:1-2,3-4,5-6,7', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 6:7-15', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-19', 'keterangan_hari' => 'Hari Raya Hati Yesus Yang Mahakudus', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yeh 34:11-16', 'mazmur_tanggapan' => 'Mzm 23:1-3,3-4,5,6', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 15:3-7', 'catatan' => 'Hari Raya, Misa wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-20', 'keterangan_hari' => 'Hari Biasa, Hati Maria Tak Bernoda', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yes 61:9-11', 'mazmur_tanggapan' => '1Sam 2:1,4-5,6-7,8', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 2:41-51', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-21', 'keterangan_hari' => 'Minggu Biasa XII', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Za 12:10-11; 13:1', 'mazmur_tanggapan' => 'Mzm 63:2,3-4,5-6,8-9', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 9:18-24', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-22', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Raj 17:5-8,13-15a,18', 'mazmur_tanggapan' => 'Mzm 60:3,4-5,12-13', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 7:1-5', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-23', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Raj 19:9b-11,14-21,31-35a,36', 'mazmur_tanggapan' => 'Mzm 48:2-3a,3b-4,10-11', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 7:6,12-14', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-24', 'keterangan_hari' => 'Hari Raya Kelahiran Yohanes Pembaptis', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yes 49:1-6', 'mazmur_tanggapan' => 'Mzm 139:1-3,13-14,14-15', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 1:57-66,80', 'catatan' => 'Hari Raya, Misa wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-25', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Raj 24:8-17', 'mazmur_tanggapan' => 'Mzm 79:1-2,3-5,8,9', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 7:21-29', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-26', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Raj 25:1-12', 'mazmur_tanggapan' => 'Mzm 137:1-2,3,4-5,6', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 8:1-4', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-27', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Rat 2:2,10-14,18-19', 'mazmur_tanggapan' => 'Mzm 74:1-2,3-4,5-6,7,20-21', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 8:5-17', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-28', 'keterangan_hari' => 'Minggu Biasa XIII', 'warna_liturgi' => 'hijau', 'bacaan1' => '1Raj 19:16b,19-21', 'mazmur_tanggapan' => 'Mzm 16:1-2,5,7-8,9-10,11', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 9:51-62', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-29', 'keterangan_hari' => 'Hari Raya S. Petrus dan Paulus', 'warna_liturgi' => 'merah', 'bacaan1' => 'Kis 12:1-11', 'mazmur_tanggapan' => 'Mzm 34:2-3,4-5,6-7,8-9', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Mat 16:13-19', 'catatan' => 'Hari Raya, Misa wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-06-30', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Am 3:1-8; 4:11-12', 'mazmur_tanggapan' => 'Mzm 5:4-5,6-7,8', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 8:23-27', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],

            // ============================================================
            // JULI 2026 (1 - 31 Juli)
            // ============================================================
            ['tanggal' => '2026-07-01', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Am 5:14-15,21-24', 'mazmur_tanggapan' => 'Mzm 50:7,8-9,10-11,12-13,16-17', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 8:28-34', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-02', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Am 7:10-17', 'mazmur_tanggapan' => 'Mzm 19:8,9,10,11', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 9:1-8', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-03', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Tomas', 'warna_liturgi' => 'merah', 'bacaan1' => 'Ef 2:19-22', 'mazmur_tanggapan' => 'Mzm 117:1,2', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Yoh 20:24-29', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-04', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Am 8:4-6,9-12', 'mazmur_tanggapan' => 'Mzm 119:2,10,20,30,40,131', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 9:9-13', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-05', 'keterangan_hari' => 'Minggu Biasa XIV', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yes 66:10-14c', 'mazmur_tanggapan' => 'Mzm 66:1-3,4-5,6-7,16,20', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 10:1-12,17-20', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-06', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Hos 2:16,17-18,21-22', 'mazmur_tanggapan' => 'Mzm 145:2-3,4-5,6-7,8-9', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 9:18-26', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-07', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Hos 8:4-7,11-13', 'mazmur_tanggapan' => 'Mzm 115:3-4,5-6,7-8,9-10', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 9:32-38', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-08', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Hos 10:1-3,7-8,12', 'mazmur_tanggapan' => 'Mzm 105:2-3,4-5,6-7', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 10:1-7', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-09', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Hos 11:1-4,8-9', 'mazmur_tanggapan' => 'Mzm 80:2-3,15-16,16', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 10:7-15', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-10', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Hos 14:2-10', 'mazmur_tanggapan' => 'Mzm 51:3-4,8-9,12-13,14,17', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 10:16-23', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-11', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Benediktus', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yes 1:10-17', 'mazmur_tanggapan' => 'Mzm 50:8-9,16-17,21,23', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 10:24-33', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-12', 'keterangan_hari' => 'Minggu Biasa XV', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Ul 30:10-14', 'mazmur_tanggapan' => 'Mzm 69:14,17,30-31,33-34,36,37', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 10:25-37', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-13', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yes 1:10-17', 'mazmur_tanggapan' => 'Mzm 50:8-9,16-17,21,23', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 10:34-11:1', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-14', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yes 7:1-9', 'mazmur_tanggapan' => 'Mzm 48:2-3a,3b-4,5-6,7-8', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 11:20-24', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-15', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Bonaventura', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yes 10:5-7,13-16', 'mazmur_tanggapan' => 'Mzm 94:5-6,7-8,9-10,14-15', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 11:25-27', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-16', 'keterangan_hari' => 'Hari Biasa, Peringatan Santa Maria dari Gunung Karmel', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yes 26:7-9,12,16-19', 'mazmur_tanggapan' => 'Mzm 102:13-14,15,16-18,19-21', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 11:28-30', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-17', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yes 38:1-6,21-22,7-8', 'mazmur_tanggapan' => 'Mzm 38:10,11,12,16', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 12:1-8', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-18', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Mi 2:1-5', 'mazmur_tanggapan' => 'Mzm 10:1-2,3-4,7-8,14', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 12:14-21', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-19', 'keterangan_hari' => 'Minggu Biasa XVI', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Kej 18:1-10a', 'mazmur_tanggapan' => 'Mzm 15:2-3,3-4,5', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 10:38-42', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-20', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Apolinaris', 'warna_liturgi' => 'merah', 'bacaan1' => 'Mi 6:1-4,6-8', 'mazmur_tanggapan' => 'Mzm 50:5-6,8-9,16-17,21,23', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 12:38-42', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-21', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Mi 7:14-15,18-20', 'mazmur_tanggapan' => 'Mzm 85:2-4,5-6,7-8', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 12:46-50', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-22', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Maria Magdalena', 'warna_liturgi' => 'putih', 'bacaan1' => 'Kid 3:1-4a', 'mazmur_tanggapan' => 'Mzm 63:2,3-4,5-6,8-9', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Yoh 20:1-2,11-18', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-23', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yer 2:1-3,7-8,12-13', 'mazmur_tanggapan' => 'Mzm 36:6-7,8-9,10-11', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 13:10-17', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-24', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yer 3:14-17', 'mazmur_tanggapan' => 'Mzm 84:2-3,4-5,7-8,10-11', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 13:18-23', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-25', 'keterangan_hari' => 'Hari Raya S. Yakobus', 'warna_liturgi' => 'merah', 'bacaan1' => '2Kor 4:7-15', 'mazmur_tanggapan' => 'Mzm 126:1-2,2-3,4-5,6', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Mat 20:20-28', 'catatan' => 'Hari Raya, Misa wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-26', 'keterangan_hari' => 'Minggu Biasa XVII', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Kej 18:20-32', 'mazmur_tanggapan' => 'Mzm 138:1-2a,2b-3,6-7,7-8', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 11:1-13', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-27', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yer 13:1-11', 'mazmur_tanggapan' => 'Mzm 85:2-3,4-5,6-7', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 13:31-35', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-28', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yer 14:17-22', 'mazmur_tanggapan' => 'Mzm 79:8-9,11,13', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 13:36-43', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-29', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Marta', 'warna_liturgi' => 'putih', 'bacaan1' => '1Yoh 4:7-16', 'mazmur_tanggapan' => 'Mzm 34:2-3,4-5,6-7,8-9,10-11', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Yoh 11:19-27', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-30', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yer 18:1-6', 'mazmur_tanggapan' => 'Mzm 146:1-2,3-4,5-6,7', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 13:47-53', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-07-31', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Ignatius Loyola', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yer 26:1-9', 'mazmur_tanggapan' => 'Mzm 69:5,8-10,14', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 13:54-58', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],

            // ============================================================
            // AGUSTUS 2026 (1 - 31 Agustus)
            // ============================================================
            ['tanggal' => '2026-08-01', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Alfonsus Maria de Liguori', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yer 26:11-16,24', 'mazmur_tanggapan' => 'Mzm 69:15-16,30-31,33-34', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 14:1-12', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-02', 'keterangan_hari' => 'Minggu Biasa XVIII', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Pkh 1:2; 2:21-23', 'mazmur_tanggapan' => 'Mzm 90:3-4,5-6,12-13,14,17', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 12:13-21', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-03', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yer 28:1-17', 'mazmur_tanggapan' => 'Mzm 119:29,43,79,80,95,102', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 14:13-21', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-04', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Yohanes Maria Vianney', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yer 30:1-2,12-15,18-22', 'mazmur_tanggapan' => 'Mzm 102:16-18,19-21,29,22-23', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 14:22-36', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-05', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yer 31:1-7', 'mazmur_tanggapan' => 'Mzm 91:2-3,4-5,6-7,14-15', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 15:21-28', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-06', 'keterangan_hari' => 'Hari Raya Yesus Menampakkan Kemuliaan-Nya', 'warna_liturgi' => 'putih', 'bacaan1' => 'Dan 7:9-10,13-14', 'mazmur_tanggapan' => 'Mzm 97:1-2,5-6,9', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Mrk 9:2-10', 'catatan' => 'Hari Raya, Misa wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-07', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yer 31:31-34', 'mazmur_tanggapan' => 'Mzm 51:12-13,14-15,18-19', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 16:13-23', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-08', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Dominikus', 'warna_liturgi' => 'putih', 'bacaan1' => 'Nah 2:1,3; 3:1-3,6-7', 'mazmur_tanggapan' => 'Ul 32:35-36,39,41', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 16:24-28', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-09', 'keterangan_hari' => 'Minggu Biasa XIX', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Keb 18:6-9', 'mazmur_tanggapan' => 'Mzm 33:1,12,18-19,20-22', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 12:32-48', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-10', 'keterangan_hari' => 'Hari Raya S. Laurensius', 'warna_liturgi' => 'merah', 'bacaan1' => '2Kor 9:6-10', 'mazmur_tanggapan' => 'Mzm 112:1-2,5-6,7-8,9', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Yoh 12:24-26', 'catatan' => 'Hari Raya, Misa wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-11', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Klara', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yeh 2:8-3:4', 'mazmur_tanggapan' => 'Mzm 119:14,24,72,103,111,131', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 18:1-5,10,12-14', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-12', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yeh 9:1-7; 10:18-22', 'mazmur_tanggapan' => 'Mzm 113:1-2,3-4,5-6', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 18:15-20', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-13', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yeh 12:1-12', 'mazmur_tanggapan' => 'Mzm 78:56-57,58-59,61-62', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 18:21-19:1', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-14', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Maksimilianus Kolbe', 'warna_liturgi' => 'merah', 'bacaan1' => 'Yeh 16:1-15,60,63', 'mazmur_tanggapan' => 'Yes 12:2-3,4,5-6', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 19:3-12', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-15', 'keterangan_hari' => 'Hari Raya Maria Diangkat ke Surga', 'warna_liturgi' => 'putih', 'bacaan1' => 'Why 11:19a; 12:1-6a,10ab', 'mazmur_tanggapan' => 'Mzm 45:10-12,16', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 1:39-56', 'catatan' => 'Hari Raya, Misa wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-16', 'keterangan_hari' => 'Minggu Biasa XX', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yer 38:4-6,8-10', 'mazmur_tanggapan' => 'Mzm 40:2-3,4,18', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 12:49-53', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-17', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yeh 24:15-24', 'mazmur_tanggapan' => 'Ul 32:18-19,20,21', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 19:16-22', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-18', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yeh 28:1-10', 'mazmur_tanggapan' => 'Ul 32:26-27,27-28,30,35-36', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 19:23-30', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-19', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yeh 34:1-11', 'mazmur_tanggapan' => 'Mzm 23:1-3,3-4,5,6', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 20:1-16', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-20', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Bernardus', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yeh 36:23-28', 'mazmur_tanggapan' => 'Mzm 51:12-13,14-15,18-19', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 22:1-14', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-21', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Pius X', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yeh 37:1-14', 'mazmur_tanggapan' => 'Mzm 107:2-3,4-5,6-7,8-9', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 22:34-40', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-22', 'keterangan_hari' => 'Hari Biasa, Peringatan Santa Perawan Maria Ratu', 'warna_liturgi' => 'putih', 'bacaan1' => 'Yes 9:1-6', 'mazmur_tanggapan' => 'Mzm 113:1-2,3-4,5-7,8', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Luk 1:26-38', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-23', 'keterangan_hari' => 'Minggu Biasa XXI', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Yes 66:18-21', 'mazmur_tanggapan' => 'Mzm 117:1,2', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 13:22-30', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-24', 'keterangan_hari' => 'Hari Raya S. Bartolomeus', 'warna_liturgi' => 'merah', 'bacaan1' => 'Why 21:9b-14', 'mazmur_tanggapan' => 'Mzm 145:10-11,12-13,17-18', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Yoh 1:45-51', 'catatan' => 'Hari Raya, Misa wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-25', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Tes 1:1-5,11-12', 'mazmur_tanggapan' => 'Mzm 96:1-2,2-3,4-5', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 23:13-22', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-26', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '2Tes 2:1-3a,14-17', 'mazmur_tanggapan' => 'Mzm 96:10,11-12,13', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 23:23-26', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-27', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Monika', 'warna_liturgi' => 'putih', 'bacaan1' => '2Tes 3:6-10,16-18', 'mazmur_tanggapan' => 'Mzm 128:1-2,4-5', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 23:27-32', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-28', 'keterangan_hari' => 'Hari Biasa, Peringatan S. Agustinus', 'warna_liturgi' => 'putih', 'bacaan1' => '1Kor 1:1-9', 'mazmur_tanggapan' => 'Mzm 145:2-3,4-5,6-7,8-9', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mat 24:42-51', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-29', 'keterangan_hari' => 'Hari Biasa, Peringatan Wafatnya Yohanes Pembaptis', 'warna_liturgi' => 'merah', 'bacaan1' => 'Yer 1:17-19', 'mazmur_tanggapan' => 'Mzm 71:1-2,3-4,5-6,15,17', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Mrk 6:17-29', 'catatan' => 'Peringatan Wajib', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-30', 'keterangan_hari' => 'Minggu Biasa XXII', 'warna_liturgi' => 'hijau', 'bacaan1' => 'Sir 3:17-18,20,28-29', 'mazmur_tanggapan' => 'Mzm 68:4-5,6-7,10-11', 'bait_pengantarinjil' => 'Alleluia, Alleluia', 'bacaan_injil' => 'Luk 14:1,7-14', 'catatan' => 'Minggu Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['tanggal' => '2026-08-31', 'keterangan_hari' => 'Hari Biasa', 'warna_liturgi' => 'hijau', 'bacaan1' => '1Kor 2:1-5', 'mazmur_tanggapan' => 'Mzm 119:97,98,99,100,101,102', 'bait_pengantarinjil' => 'Alleluia', 'bacaan_injil' => 'Luk 4:16-30', 'catatan' => 'Hari Biasa', 'is_active' => 1, 'created_at' => now(), 'updated_at' => now()],
        ];

        // Insert menggunakan DB
        DB::table('kalender_liturgi_hari')->insert($data);
        
        // Debug: Tampilkan jumlah data
        $count = KalenderLiturgiHari::count();
        $this->command->info("✅ Berhasil menambahkan {$count} data kalender liturgi (Juni - Agustus 2026)");
        
        // Aktifkan kembali foreign key checks
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}